# Generated by Django 4.0.4 on 2022-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='biography',
        ),
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.TextField(blank=True, null=True, verbose_name='Избранные курсы'),
        ),
        migrations.CreateModel(
            name='CourseChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eigth', models.ManyToManyField(blank=True, related_name='seventh1', to='dmk.course', verbose_name='8 предмет')),
                ('fifth', models.ManyToManyField(blank=True, related_name='forth1', to='dmk.course', verbose_name='5 предмет')),
                ('first', models.ManyToManyField(blank=True, related_name='ebat_moi_hui1', to='dmk.course', verbose_name='1 предмет')),
                ('forth', models.ManyToManyField(blank=True, related_name='third1', to='dmk.course', verbose_name='4 предмет')),
                ('ninth', models.ManyToManyField(blank=True, related_name='eigth1', to='dmk.course', verbose_name='9 предмет')),
                ('second', models.ManyToManyField(blank=True, related_name='first1', to='dmk.course', verbose_name='2 предмет')),
                ('seventh', models.ManyToManyField(blank=True, related_name='sixth1', to='dmk.course', verbose_name='7 предмет')),
                ('sixth', models.ManyToManyField(blank=True, related_name='fifth1', to='dmk.course', verbose_name='6 предмет')),
                ('tenth', models.ManyToManyField(blank=True, related_name='ninth1', to='dmk.course', verbose_name='10 предмет')),
                ('third', models.ManyToManyField(blank=True, related_name='second1', to='dmk.course', verbose_name='3 предмет')),
            ],
            options={
                'verbose_name': 'Цепочка',
                'verbose_name_plural': 'Цепочки',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='presets',
            field=models.ManyToManyField(blank=True, null=True, to='dmk.coursechain'),
        ),
    ]
