# Generated by Django 4.0.4 on 2022-06-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmk', '0006_course_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='presets',
            field=models.ManyToManyField(blank=True, null=True, to='dmk.professiondetail'),
        ),
    ]
