# Generated by Django 4.0.4 on 2022-06-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmk', '0007_alter_user_presets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Изображение'),
        ),
    ]
