# Generated by Django 4.0.4 on 2022-06-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmk', '0008_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='year',
            field=models.CharField(choices=[('2017', 2017), ('2018', 2018), ('2019', 2019), ('2020', 2020), ('2021', 2021), ('2017-2021', 2022)], max_length=255, unique=True, verbose_name='Год'),
        ),
    ]
